services:

    getmail-mailcow:
      pull_policy: never
      build: /opt/mailcow-getmail/Dockerfiles
      environment:
        - TZ=${TZ}
      volumes:
        - /opt/mailcow-getmail/conf/settings.ini:/app/settings.ini:ro
      depends_on:
        clamd-mailcow:
          condition: service_healthy
        dovecot-mailcow:
          condition: service_started
      restart: always
      mem_limit: 1g
      mem_reservation: 100m
      networks:
        mailcow-network:
          aliases:
            - getmail    
